# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SH1ksCxxpqBLRxElcfJG8MHN1DbXupW0
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import json

st.set_page_config(page_title="Dashboard Pembangunan Wilayah Jatim", layout="wide")

@st.cache_data
def load_data():
    df = pd.read_csv('dataset_final_v4.csv')
    with open('Provinsi_Jawa_Timur-KAB_KOTA.geojson', encoding='utf-8') as f:
        geojson_data = json.load(f)
    return df, geojson_data

df, geojson_data = load_data()

df = df.sort_values('nomor_kategori')
daftar_kategori = df.drop_duplicates('nomor_kategori').sort_values('nomor_kategori')['label_lengkap'].tolist()

palet_warna_urut = ['#e74c3c', '#f1c40f', '#3498db', '#2ecc71', '#9b59b6', '#1abc9c']
color_map = {kategori: palet_warna_urut[i % len(palet_warna_urut)] for i, kategori in enumerate(daftar_kategori)}

FORMAT_KOLOM = {
    'ipm': '{:.2f}',
    'persentase_miskin': '{:.2f}%',
    'rls': '{:.2f}',
    'tpt': '{:.2f}%',
    'pdrb_per_kapita': '{:,.0f}',
    'total_faskes': '{:,.0f}'
}

st.sidebar.title("📊 Navigasi Dashboard")
menu = st.sidebar.radio("Pilih Halaman:", ["Overview", "Peta Klaster", "Perbandingan Klaster", "Hasil Regresi", "Eksplorasi Data"])

st.sidebar.markdown("---")
st.sidebar.markdown("**Sumber Data:** Open Data Jatim & BPS Jatim, 2025")
st.sidebar.markdown("**Metode:** K-Means Clustering (berbasis IPM) & Regresi Linier Berganda")

if menu == "Overview":
    st.title("🗺️ Dashboard Pembangunan Wilayah Jawa Timur")
    st.markdown("Analisis klasterisasi dan faktor determinan pembangunan 38 kabupaten/kota di Jawa Timur, tahun 2025.")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Jumlah Wilayah", f"{df.shape[0]}")
    col2.metric("Rata-rata IPM", f"{df['ipm'].mean():.2f}")
    col3.metric("Rata-rata TPT", f"{df['tpt'].mean():.2f}%")
    col4.metric("Jumlah Kategori", f"{df['label_lengkap'].nunique()}")

    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Distribusi Wilayah per Kategori")
        klaster_count = df.groupby('nomor_kategori')['label_lengkap'].agg(['first', 'count']).reset_index()
        klaster_count.columns = ['nomor_kategori', 'Kategori', 'Jumlah Wilayah']
        fig = px.pie(klaster_count, names='Kategori', values='Jumlah Wilayah',
                     color='Kategori', color_discrete_map=color_map,
                     category_orders={'Kategori': daftar_kategori})
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Ranking IPM Tertinggi & Terendah")
        top5 = df.nlargest(5, 'ipm')[['wilayah', 'ipm']]
        bottom5 = df.nsmallest(5, 'ipm')[['wilayah', 'ipm']]
        tab1, tab2 = st.tabs(["5 Tertinggi", "5 Terendah"])
        with tab1:
            st.dataframe(top5.style.format({'ipm': '{:.2f}'}), use_container_width=True, hide_index=True)
        with tab2:
            st.dataframe(bottom5.style.format({'ipm': '{:.2f}'}), use_container_width=True, hide_index=True)

    st.markdown("---")
    st.subheader("Ranking Seluruh Wilayah Berdasarkan IPM")
    df_sorted = df.sort_values('ipm', ascending=True)
    fig = px.bar(df_sorted, x='ipm', y='wilayah', orientation='h', color='label_lengkap',
                 color_discrete_map=color_map, category_orders={'label_lengkap': daftar_kategori},
                 height=800, labels={'ipm': 'IPM', 'wilayah': 'Wilayah', 'label_lengkap': 'Kategori'})
    fig.update_yaxes(categoryorder='array', categoryarray=df_sorted['wilayah'])
    st.plotly_chart(fig, use_container_width=True)

elif menu == "Peta Klaster":
    st.title("🗺️ Peta Sebaran Kategori Wilayah")

    variabel_peta = st.selectbox(
        "Tampilkan berdasarkan:",
        ['label_lengkap', 'ipm', 'persentase_miskin', 'pdrb_per_kapita', 'tpt']
    )

    if variabel_peta == 'label_lengkap':
        fig = px.choropleth(
            df, geojson=geojson_data, locations='wilayah',
            featureidkey='properties.kab_kota', color='label_lengkap',
            color_discrete_map=color_map, category_orders={'label_lengkap': daftar_kategori},
            hover_name='wilayah',
            hover_data={'ipm': ':.2f', 'pdrb_per_kapita': ':,.0f', 'tpt': ':.2f', 'wilayah': False},
            labels={'label_lengkap': 'Kategori'}
        )
    else:
        fig = px.choropleth(
            df, geojson=geojson_data, locations='wilayah',
            featureidkey='properties.kab_kota', color=variabel_peta,
            color_continuous_scale='YlOrRd', hover_name='wilayah',
            hover_data={'label_lengkap': True, 'wilayah': False}
        )

    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(height=650, margin={"r": 0, "t": 30, "l": 0, "b": 0})
    st.plotly_chart(fig, use_container_width=True)
    st.info("💡 Arahkan kursor ke tiap wilayah pada peta untuk melihat detail data.")

elif menu == "Perbandingan Klaster":
    st.title("🔍 Perbandingan Karakteristik Antar Kategori")

    variabel_pilihan = st.selectbox(
        "Pilih variabel untuk dibandingkan:",
        ['ipm', 'persentase_miskin', 'rls', 'tpt', 'pdrb_per_kapita', 'total_faskes']
    )

    label_variabel = {
        'ipm': 'Indeks Pembangunan Manusia', 'persentase_miskin': 'Persentase Penduduk Miskin (%)',
        'rls': 'Rata-Rata Lama Sekolah (tahun)', 'tpt': 'Tingkat Pengangguran Terbuka (%)',
        'pdrb_per_kapita': 'PDRB per Kapita (ribu rupiah)', 'total_faskes': 'Total Fasilitas Kesehatan'
    }

    col1, col2 = st.columns([1, 1])
    with col1:
        st.subheader(f"Rata-rata {label_variabel[variabel_pilihan]} per Kategori")
        rata_rata = df.groupby('label_lengkap')[variabel_pilihan].mean().reindex(daftar_kategori).reset_index()
        fig = px.bar(rata_rata, x='label_lengkap', y=variabel_pilihan, color='label_lengkap',
                     color_discrete_map=color_map, category_orders={'label_lengkap': daftar_kategori},
                     labels={'label_lengkap': 'Kategori', variabel_pilihan: label_variabel[variabel_pilihan]})
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader(f"Sebaran {label_variabel[variabel_pilihan]} per Kategori")
        fig = px.box(df, x='label_lengkap', y=variabel_pilihan, color='label_lengkap',
                     color_discrete_map=color_map, category_orders={'label_lengkap': daftar_kategori},
                     labels={'label_lengkap': 'Kategori', variabel_pilihan: label_variabel[variabel_pilihan]})
        st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("Tabel Ringkasan Karakteristik Tiap Kategori")
    tabel_ringkasan = df.groupby('label_lengkap')[
        ['ipm', 'persentase_miskin', 'rls', 'tpt', 'pdrb_per_kapita', 'total_faskes']
    ].mean().reindex(daftar_kategori)

    st.dataframe(tabel_ringkasan.style.format(FORMAT_KOLOM), use_container_width=True)

    st.markdown("---")
    st.subheader("Daftar Wilayah per Kategori")
    klaster_terpilih = st.selectbox("Pilih kategori:", daftar_kategori)
    wilayah_list = df[df['label_lengkap'] == klaster_terpilih][['wilayah', 'ipm']].sort_values('ipm', ascending=False)
    st.dataframe(
        wilayah_list.style.format({'ipm': '{:.2f}'}),
        use_container_width=True, hide_index=True
    )

elif menu == "Hasil Regresi":
    st.title("📈 Hasil Analisis Regresi Linier Berganda")
    st.markdown("Model regresi untuk mengetahui faktor yang paling berpengaruh terhadap IPM, menggunakan seluruh indikator yang tersedia.")

    col1, col2, col3 = st.columns(3)
    col1.metric("R-squared", "0.968")
    col2.metric("Adj. R-squared", "0.962")
    col3.metric("F-statistic p-value", "8.70e-20")

    st.markdown("---")
    hasil_regresi = pd.DataFrame({
        'Variabel': ['Konstanta', 'Persentase Miskin', 'RLS', 'TPT', 'log PDRB per Kapita', 'Total Faskes'],
        'Koefisien': [49.16, -0.0126, 2.7275, -0.0446, 0.2908, 0.0005],
        'p-value': [0.000, 0.862, 0.000, 0.868, 0.370, 0.085],
        'Signifikan (α=0.05)': ['Ya', 'Tidak', 'Ya', 'Tidak', 'Tidak', 'Tidak']
    })
    st.subheader("Tabel Koefisien Regresi")
    st.dataframe(hasil_regresi, use_container_width=True, hide_index=True)

    st.markdown("---")
    st.subheader("Visualisasi Kekuatan Pengaruh Tiap Variabel")
    fig = px.bar(hasil_regresi[hasil_regresi['Variabel'] != 'Konstanta'],
                 x='Variabel', y='Koefisien', color='Koefisien', color_continuous_scale='RdYlGn',
                 labels={'Koefisien': 'Koefisien Regresi'})
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("Interpretasi Hasil")
    st.markdown("""
    - **Rata-Rata Lama Sekolah (RLS)** adalah satu-satunya variabel yang signifikan (p=0.000), dengan pengaruh
      positif besar terhadap IPM. Ini konsisten dengan fakta bahwa RLS merupakan komponen langsung pembentuk
      Indeks Pendidikan dalam rumus IPM.
    - **Persentase Kemiskinan, TPT, PDRB per Kapita, dan Total Faskes** tidak signifikan pada model ini
      (p-value semuanya di atas 0.05). Hal ini **bukan berarti keempatnya tidak berpengaruh terhadap pembangunan
      wilayah secara riil**, melainkan pengaruhnya secara statistik tertutupi oleh dominasi RLS dalam model.
    - **R-squared sebesar 0,968** tergolong sangat tinggi untuk data sosial-ekonomi, dan perlu dibaca dengan
      hati-hati mengingat adanya unsur *circularity* dari variabel RLS, bukan semata-mata menunjukkan kualitas
      model yang sangat baik.
    """)

elif menu == "Eksplorasi Data":
    st.title("🔎 Eksplorasi Data Wilayah")

    col1, col2 = st.columns([1, 3])
    with col1:
        filter_klaster = st.multiselect("Filter Kategori:", daftar_kategori, default=daftar_kategori)

    df_filtered = df[df['label_lengkap'].isin(filter_klaster)]

    st.subheader(f"Data Wilayah ({len(df_filtered)} wilayah)")
    kolom_tampil = ['wilayah', 'label_lengkap', 'ipm', 'persentase_miskin', 'rls', 'tpt', 'pdrb_per_kapita', 'total_faskes']
    st.dataframe(
        df_filtered[kolom_tampil].style.format(FORMAT_KOLOM),
        use_container_width=True, hide_index=True
    )

    st.markdown("---")
    st.subheader("Cari Wilayah Spesifik")
    wilayah_cari = st.selectbox("Pilih wilayah:", sorted(df['wilayah'].unique()))
    data_wilayah = df[df['wilayah'] == wilayah_cari].iloc[0]

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("IPM", f"{data_wilayah['ipm']:.2f}")
    col2.metric("PDRB per Kapita", f"{data_wilayah['pdrb_per_kapita']:,.0f}")
    col3.metric("TPT", f"{data_wilayah['tpt']:.2f}%")
    col4.metric("Kategori", data_wilayah['label_lengkap'])

    st.markdown("---")
    st.subheader("Download Data")
    csv = df_filtered.to_csv(index=False).encode('utf-8')
    st.download_button("📥 Download CSV", csv, "data_wilayah_jatim.csv", "text/csv")